### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [paopaonetizen/website#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by hye** [comment]
@karan Please don't bother, they are not open-sourcing a project, just to place their option to get political refuge .
And they use bot to commit, so they may never check this issue.

**Comment by paopaonetizen** [comment]
Hi, Thank you for informing. We did look at your suggestion/ticket but we are not sure how to proceed...

PaoPao..
